service: api

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

functions:
  hello:
    handler: handler.getDetailedTeamUsage
    events:
      - http:
          path: /
          method: get
          cors: true