service: api

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  environment:
    mongo_url: ${env:mongo_url}
    mongo_db: ${env:mongo_db}

functions:
  createGame:
    handler: handler.createGame
    events:
      - http:
          path: /games
          method: post
          cors: true
  listGames:
    handler: handler.listGames
    events:
      - http:
          path: /games
          method: get
          cors: true