name: dev

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      working-directory: ./api

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.13.1
      uses: actions/setup-node@v1
      with:
        node-version: 12.16.0
    - name: install
      working-directory: ${{env.working-directory}}
      run: npm ci
    - name: deploy
      working-directory: ${{env.working-directory}}
      run: npx serverless deploy --stage=dev
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        mongo_url: ${{ secrets.mongo_url }}
        mongo_db: ${{ secrets.mongo_db }}


